# Generated by Django 4.1.6 on 2023-06-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_audio_audio_audio_user_id_audio_user_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='user_uuid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
